server:
  port: 8090
  servlet:
    session:
      timeout: 1h
      cookie:
        secure: true

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring.redis:
  host: localhost
  port: 6379

spring.profiles.include: custom
