server:
  port: 8090

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring.h2:
    console:
      enabled: true

spring.datasource:
  url: jdbc:h2:mem:user-db

spring.jpa:
  hibernate.ddl-auto: update
  open-in-view: false

spring.profiles.include: custom